# Site settings
title: KWH Windows and Doors
email: info@kwh.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

phone_number: "07704382597"
twitter_username:
facebook_page: KWH

# Build settings
markdown: kramdown
